version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "50m" 

services:

  postgres-db:
    <<: *default-opts
    image: postgres:13.3-alpine
    environment:
      POSTGRES_PASSWORD: DB_PASS
      POSTGRES_USER: DB_USER
      POSTGRES_DB: FBG_DB
    networks: 
        - traefik_network
    volumes: 
      - fbg-postgres-db:/var/lib/postgresql/data

  web:
    <<: *default-opts
    image: shjgames/web
    # ports:
    #   - '3000:3000'
    environment:
      SERVER_TYPE: 'WEB'
      FBG_BACKEND_TARGET: 'http://backend:3001'
    networks: 
      - traefik_network
    deploy: 
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fbg-web.rule=Host(`test1.sahajanand-games.com`)"
      - "traefik.http.routers.fbg-web.entrypoints=web-secure"
      - "traefik.http.routers.fbg-web.tls=true"
      - "traefik.http.routers.fbg-web.service=fbg-web"
      - "traefik.http.services.fbg-web.loadbalancer.server.port=3000"
      # apply redirect from non-www to www
      - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www.test1.sahajanand-games.com/(.*)"
      - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://test1.sahajanand-games.com/$${1}"
      - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.www-redirect.rule=Host(`www.test1.sahajanand-games.com`)"
      - "traefik.http.routers.www-redirect.entrypoints=web-secure"
      - "traefik.http.routers.www-redirect.middlewares=www-redirect"
      - "traefik.http.routers.www-redirect.tls=true"
  
  bgio:
    <<: *default-opts
    image: shjgames/web
    environment:
      SERVER_TYPE: 'BGIO'
      BGIO_PORT: 8001
      POSTGRES_URL: postgresql://DB_USER:DB_PASS@postgres-db:5432/FBG_DB
    # ports:
    #   - '8001:8001'
    networks: 
      - traefik_network
    deploy: 
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fbg-bgio.rule=Host(`test1.sahajanand-games.com`) && Path(`/socket.io/`)"
      - "traefik.http.routers.fbg-bgio.entrypoints=web-secure"
      - "traefik.http.routers.fbg-bgio.tls=true"
      - "traefik.http.routers.fbg-bgio.service=fbg-bgio"
      - "traefik.http.services.fbg-bgio.loadbalancer.server.port=8001"
  
  backend:
    <<: *default-opts
    image: shjgames/fbg-server
    environment: 
      BGIO_PUBLIC_SERVERS: 'https://test1.sahajanand-games.com'
      BGIO_PRIVATE_SERVERS: 'http://bgio:8001'
      JWT_SECRET: 'SomethingVerySecret'
      POSTGRES_URL: postgresql://DB_USER:DB_PASS@postgres-db:5432/FBG_DB
    # ports:
    #   - '3001:3001'
    networks: 
      - traefik_network
    deploy: 
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.fbg-backend.rule=Host(`test1.sahajanand-games.com`) && Path(`/graphql`)"
        - "traefik.http.routers.fbg-backend.entrypoints=web-secure"
        - "traefik.http.routers.fbg-backend.tls=true"
        - "traefik.http.routers.fbg-backend.service=fbg-backend"
        - "traefik.http.services.fbg-backend.loadbalancer.server.port=3001"

  traefik:
    <<: *default-opts
    image: "traefik:v2.4"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.endPoint=http://dockersocket:2375"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_network"
      - "--entrypoints.web-insecure.address=:80"
      - "--entrypoints.web-insecure.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web-insecure.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web-secure.address=:443"
      - "--accesslog"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    # volumes:
    #   - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: 
      - traefik_network

  dockersocket:
    <<: *default-opts
    image: tecnativa/docker-socket-proxy
    networks:
      - traefik_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1

networks:
  traefik_network:
    external: true

volumes: 
  fbg-postgres-db: 
    external: true
